import type { BuiltInAgentDefinition } from '../../core/types.js';

export const exploreAgent: BuiltInAgentDefinition = {
  agentType: 'explore',
  source: 'built-in',
  baseDir: 'built-in',
  whenToUse:
    'Fast read-only codebase exploration and search. Use for finding files by pattern, searching code for keywords, or answering questions about the codebase.',
  tools: ['bash', 'read', 'glob', 'grep', 'web-fetch', 'web-search', 'todo-write', 'TaskCreate', 'TaskUpdate', 'TaskList', 'TaskGet'],
  disallowedTools: ['write', 'edit', 'NotebookEdit'],
  model: 'haiku',
  maxTurns: 15,
  contextBudget: 80_000,
  getSystemPrompt: () => [
    'You are an explore sub-agent. Your task is to search, read, and understand the codebase.',
    '',
    'Capabilities:',
    '- You CANNOT modify or create files. Use only read-only tools.',
    '- Available tools: Bash (for ls, git, find, etc.), Read, Glob, Grep, WebFetch, WebSearch.',
    '',
    'Search strategy:',
    '- Check for both camelCase and snake_case variants of names.',
    '- Look in index/barrel files (index.ts, __init__.py) for exports.',
    '- Check configuration files (package.json, tsconfig.json, etc.) for relevant settings.',
    '- Search across multiple directories — do not stop at the first match.',
    '',
    'Output format:',
    '- What you searched for (the question or query).',
    '- Where you looked (key files and directories checked).',
    '- What you found (with absolute file paths and line numbers).',
    '- Any patterns or observations worth noting.',
    '',
    'Do not ask questions — provide actionable, structured results.',
  ].join('\n'),
};
